language: go
go:
  - 1.13.x
arch:
  - arm64
  - amd64
env:
  matrix:
  - GO111MODULE=on
  - BINDIR=bin
  global:
    secure: HAIH4Q6plJRjoZPMCzWldSY0d+hHFj3BuPXXstArHZrKjIyrpws3EoFBdG08IRrkDs+gemhbDGj1jc6+DhJ3KBmDLZr0i4jmsx+tNn6P0+9mv/vPnOygjrR4t9T3SYE/B/GDSyMiQCCz4KUOPQXKPqGqsUKVAwl6znu/lwthl2M476aAY/UPnyodgz5M6okUnL2yPa2b65Uehu79+YotcJk8RsFSRCs0VSNycrtfVG9HIyOJCwaP2MnXZQLs2d+ld6bC2ARRckkvbcugliGYJnduTcoYOksPeEsK+R4bxT4mZ3RbMLpORdMFEZLAmkQLR8PglhGKdheFnhy//OrD7v0+3B4ycinVTnhD8nomS83oDpWMVz8w4cfiL4sOKcCLcqTjQovjVW/uFzCg6FnAEZ9Sr4PG6pwoz3NpNbIzOabI/ey5Ke/E1VZ6Up7unoREUErPcIIuPyP/98WoInQGZ8abtMt8WoEuKye8b1tWz44OsLoXq7V4sPFRagTBnbGgmt7lpPMfNVVCqYmaEkFOFgD42Zi9aC0GqPB7f0tVkoRLc9ghOIFPq+cIm0E8Vo42CBzR9a9Mf2/v6VX1KS03XoX5SlW9ieM+CO1wVvSGbclYMMHDkQXWDwYCBlostrLObeIoivwSc60+zXokfPO5D4xWHh+AskZXxkEdbKFQsso=
script:
- make
deploy:
  provider: releases
  api_key:
    secure: "hzykNqqyF+YuiTyQfBBAord/nWircpDI7F0kPvR6Oh3FM3/FNxOa/mTs6FpuVGzAzY08WNv29Q8kQlcT4fsTzR0ZX1oi9enYjbIR5qs9pCMmAbJpHYuPeW0kelh3Qn1DjVg76vJ4quz3eFIZPFwvtyvo1wHJ5Wcc+oxu/Ss/FP/DmP/tuOjEUJcWVYppNma5O7paUgivThtoKSuHtj+DgKLMm5sBB8253x0rdWgp0geH8zb1T1m/S9yRNnvnWHqWC0K3dO8b+hKSBDKSHC9X9U/voNuLiD2Qdyt7KaTbgGiuJIzo1lB76c3fTofcoc0upW00BuKsruWx7/QQEPaxmEPRpycR46yhkQE7vKj+cYRKsJZshBTjvUpEYWlXviQIeQ2gfqMe+YcZesXuGcm2EG0zUorGlyydBBGp4do9YAQUczSGZOV6SiPbHZYC5pGxgiTvX6mHAnWSgVhBDDOWfhWGO2pR3dw+8qUr+w7I0OVq+hT890uhrYsH8C8+6E+kNmTCH7fQFB6JPNFQVzt0yTaHVh5v4Air9e/ZqapGcmRxNOmyi8Kp1p6ck+it+7aRsw4+45h097fpWK7yNDLnJw3f6GcS0HY8JNedNDGFty+/Gv8vC2b1dcweg2o7+baFNKOuCKkx92D6yrSSwu2NulAXNc97zqB//EkHtYYdWko=" 
  file: ${BINDIR}/*
  skip_cleanup: true
  on:
    tags: true
